name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: Q1k6nP4jnyo498QSJtd7rnBCthbbdCZT:60cb94f44029095cf4a2eda2
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: 'petstore.json'
          api-version: 'v1.1.0'
